# “Вычисления с помощью Numpy”

In [20]:
import numpy as np

Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [31]:
# task_1
# создание массива
c1 = [1, 2, 3, 3, 1]
c2 = [6, 8, 11, 10, 7]
a = np.stack((c1, c2), axis=1)
print (a)


[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [32]:
# нахождение среднего значения по признаку (столбцу)
mean_a = a.mean(axis=0)
print (mean_a)


[2.  8.4]


Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, 
содержащиеся в массиве mean_a. 
Вычисление должно производиться в одно действие. 
Получившийся массив должен иметь размер 5x2.

In [33]:
# вычисление массива a_centered
a_centered = a - mean_a
print (a_centered)


[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [27]:
# проверка размера
print (f'Форма: {a_centered.shape}')

Форма: (5, 2)


Задание 3
Найдите скалярное произведение столбцов массива a_centered. 
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [28]:
# нахождение сколярного произведения
# a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp

8.0

In [29]:
# нахождение ковариации
a_cov = a_centered_sp / (a.shape[0] - 1)
a_cov

2.0

Задание 4**
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. 
В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, 
поэтому полученная нами величина является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:
Выборочная ковариация и выборочная дисперсия — Студопедия
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. 
В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. 
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение 
ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [30]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])